[style] globalStyle 및 theme 적용 & 스토리북 ThemeProvider 기본 설정
woowa-techcamp-2021/store-10 pull request #20
Opened 2021-08-11 09:31 UTC by KangyeolLee

## 개요 및 변경 사항 

- GlobalStyle에 사용할 속성 간단한 사항 추가 (해상도 관련 / Link(a tag) 기본 속성 제거)
- theme에 다크모드/라이트모드 관련 색상 추가 (ThemeProvider로 내려주도록 설정)
- DefaultTheme 관련 커스텀 타입 선언
- 스토리북 styled-components 관련 라이브러리 및 데코레이터 적용 시도

## 관련 이슈 

closes #10 
#17 

## 추가 구현 필요사항

- 스토리북에서 아직 styled-components를 제대로 인식하지 못하고 있습니다. 관련해서 더 알아보아야 할 것 같으네용...

## 스크린샷

없음

2021-08-11 09:33 UTC, HanCheo approved these changes
옙 확인했습니당~~~ : )

2021-08-11 09:33 UTC, Kyun2da requested changes
엇 강열님 피그마 관련 패키지 json이 루트 폴더에 설치 되있어요! 혹시 이것 때문..?

2021-08-11 09:39 UTC, KangyeolLee commented
> 엇 강열님 피그마 관련 패키지 json이 루트 폴더에 설치 되있어요! 혹시 이것 때문..? 일단 아니더라도 지우셔야 할 것 같아요!

오잉 그게 혹시 어떤 파일인가요??

2021-08-11 09:40 UTC, Kyun2da commented
> > 엇 강열님 피그마 관련 패키지 json이 루트 폴더에 설치 되있어요! 혹시 이것 때문..? 일단 아니더라도 지우셔야 할 것 같아요!
> 
> 오잉 그게 혹시 어떤 파일인가요??

아 파일 변경 내역 보시면 client 파일 안의 패키지 json이 아니라 최상위 폴더에 package.json이랑 package.lock.json이랑 만들어져있어요

2021-08-11 09:40 UTC, Kyun2da commented on package.json
> +}
얘네들이요!

2021-08-11 09:41 UTC, KangyeolLee commented
> > > 엇 강열님 피그마 관련 패키지 json이 루트 폴더에 설치 되있어요! 혹시 이것 때문..? 일단 아니더라도 지우셔야 할 것 같아요!
> > 
> > 
> > 오잉 그게 혹시 어떤 파일인가요??
> 
> 아 파일 변경 내역 보시면 client 파일 안의 패키지 json이 아니라 최상위 폴더에 package.json이랑 package.lock.json이랑 만들어져있어요

오우 ㅅ슅! ㅋㅋㅋ 죄성죄성 어쩐지 뭘 까는데 한참 걸리더라... 수정하고 다시 커밋하겠습니다

2021-08-11 09:41 UTC, KangyeolLee commented on package.json
> +}
넵넵 확인 완료!! 수정하고 다시 해보고 커밋할게요! 될 거 같기도?
어쩐지 왜 안 보이나 했습니다

2021-08-11 09:44 UTC, KangyeolLee commented on package.json
> +}
ㅋㅋㅋ 오늘도 내다버린 한 시간....
넘나 잘 되는군요 ㅠㅠ

2021-08-11 09:48 UTC, dongqui approved these changes

2021-08-11 09:48 UTC, dongqui commented on client/src/styles/styled.d.ts
> +declare module 'styled-components' {
덕분에 d.ts, declare 알게 되었습니다..! 👍

2021-08-11 10:18 UTC, KangyeolLee commented on client/src/styles/styled.d.ts
> +declare module 'styled-components' {
앞으로 많이 마주하게 되실겁니다.. 또르륵

2021-08-11 10:20 UTC, merged

2021-08-13 06:56 UTC, jiho9505 commented
ThemeProvider에 대해 알고갑니다 껄껄